POST http://localhost:3000/api/signup HTTP/1.1
Content-Type: application/json

{
    "username": "Saurabh",
    "email": "saurabh7481@gmail.com",
    "phone": "9868715540",
    "password": "123456"
}

###

POST http://localhost:3000/api/expense/addexpense HTTP/1.1
Content-Type: application/json

{
    "description": "Party!!",
    "amount": "450",
    "category": "Entertainment"
}